// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Deployment contracts: render the public values interface and compare backends
//! with Services generated by the real Tenant implementation. Helm is required.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use operator::types::v1alpha1::tenant::Tenant;
use serde::Deserialize;
use serde_yaml_ng::Value;
use std::io::Write;
use std::path::Path;
use std::process::{Command, Output, Stdio};

fn render(values: &str, files: &[&str]) -> Output {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut command = Command::new("helm");
    command.current_dir(root).args([
        "template",
        "rustfs",
        "deploy/rustfs-tenant",
        "--namespace",
        "rustfs-storage",
    ]);
    for file in files {
        command.args(["--values", file]);
    }
    let mut child = command
        .args(["--values", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("install Helm 3 to run Tenant chart contract tests");
    child
        .stdin
        .take()
        .unwrap()
        .write_all(values.as_bytes())
        .unwrap();
    child.wait_with_output().unwrap()
}

fn documents(output: Output) -> Vec<Value> {
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    serde_yaml_ng::Deserializer::from_slice(&output.stdout)
        .map(|doc| Value::deserialize(doc).unwrap())
        .filter(|doc| !doc.is_null())
        .collect()
}

fn tenant(docs: &[Value]) -> Tenant {
    let doc = docs.iter().find(|doc| doc["kind"] == "Tenant").unwrap();
    let tenant: Tenant = serde_yaml_ng::from_value(doc.clone()).unwrap();
    tenant.validate_name().unwrap();
    tenant.validate_pools().unwrap();
    tenant
}

fn assert_resource_boundary(docs: &[Value]) {
    for doc in docs {
        assert!(
            ["Tenant", "Ingress", "HTTPRoute", "BackendTLSPolicy"]
                .contains(&doc["kind"].as_str().unwrap())
        );
        assert_eq!(doc["metadata"]["namespace"], "rustfs-storage");
        assert!(doc["metadata"]["ownerReferences"].is_null());
    }
}

#[test]
fn default_chart_only_creates_a_tenant() {
    let docs = documents(render("{}", &[]));
    assert_eq!(docs.len(), 1);
    let tenant = tenant(&docs);
    assert_eq!(tenant.metadata.name.as_deref(), Some("rustfs"));
    assert_eq!(tenant.spec.creds_secret.unwrap().name, "rustfs-credentials");
    assert_resource_boundary(&docs);
}

#[test]
fn native_tenant_fields_and_metadata_survive_without_template_evaluation() {
    let docs = documents(render(
        r#"
tenant:
  metadata:
    name: warehouse
    labels: {team: storage}
    annotations: {literal: '{{ .Release.Name }}'}
  spec:
    image: registry.example.com/rustfs:tested
    env:
      - name: RUSTFS_SERVER_DOMAINS
        value: s3.example.com
      - name: CUSTOM_TOKEN
        valueFrom:
          secretKeyRef: {name: application-token, key: token}
    network:
      ipFamilyPolicy: PreferDualStack
      ipFamilies: [IPv4, IPv6]
    pools:
      - name: primary
        servers: 4
        persistence:
          volumesPerServer: 4
"#,
        &["deploy/rustfs-tenant/examples/ingress.yaml"],
    ));
    let tenant = tenant(&docs);
    assert_eq!(tenant.metadata.name.as_deref(), Some("warehouse"));
    assert_eq!(
        tenant.metadata.annotations.as_ref().unwrap()["literal"],
        "{{ .Release.Name }}"
    );
    assert_eq!(tenant.spec.env.len(), 2);
    assert!(tenant.spec.env[1].value_from.is_some());
    assert_eq!(tenant.spec.pools[0].servers, 4);
    assert!(tenant.spec.network.is_some());
    let ingress = docs
        .iter()
        .find(|d| d["metadata"]["name"] == "warehouse-api")
        .unwrap();
    assert_eq!(
        ingress["spec"]["rules"][0]["http"]["paths"][0]["backend"]["service"]["name"],
        "warehouse-io"
    );
    assert_resource_boundary(&docs);
}

#[test]
fn ingress_backends_match_operator_services_and_preserve_tls() {
    let docs = documents(render(
        "{}",
        &["deploy/rustfs-tenant/examples/ingress.yaml"],
    ));
    assert_eq!(docs.len(), 3);
    let tenant = tenant(&docs);
    for (endpoint, service) in [
        ("api", tenant.new_io_service()),
        ("console", tenant.new_console_service()),
    ] {
        let name = format!("rustfs-{endpoint}");
        let ingress = docs.iter().find(|d| d["metadata"]["name"] == name).unwrap();
        let path = &ingress["spec"]["rules"][0]["http"]["paths"][0];
        assert_eq!(path["path"], "/");
        assert_eq!(path["pathType"], "Prefix");
        assert_eq!(
            path["backend"]["service"]["name"],
            service.metadata.name.unwrap()
        );
        assert_eq!(
            path["backend"]["service"]["port"]["number"]
                .as_i64()
                .unwrap(),
            i64::from(service.spec.unwrap().ports.unwrap()[0].port)
        );
        assert_eq!(ingress["spec"]["tls"][0]["secretName"], "rustfs-edge-tls");
    }
    assert_resource_boundary(&docs);
}

#[test]
fn gateway_preserves_parent_refs_timeouts_and_virtual_hostnames() {
    let docs = documents(render(
        r#"
httpRoute:
  api:
    timeouts: {request: 600s, backendRequest: 600s}
"#,
        &[
            "deploy/rustfs-tenant/examples/gateway.yaml",
            "deploy/rustfs-tenant/examples/virtual-hosted.yaml",
        ],
    ));
    assert_eq!(docs.len(), 3);
    let tenant = tenant(&docs);
    assert_eq!(tenant.spec.env[0].value.as_deref(), Some("s3.example.com"));
    for (endpoint, service) in [
        ("api", tenant.new_io_service()),
        ("console", tenant.new_console_service()),
    ] {
        let name = format!("rustfs-{endpoint}");
        let route = docs.iter().find(|d| d["metadata"]["name"] == name).unwrap();
        let parent = &route["spec"]["parentRefs"][0];
        assert_eq!(parent["namespace"], "gateway-system");
        assert_eq!(parent["sectionName"], "https");
        assert_eq!(parent["kind"], "Gateway");
        let rule = &route["spec"]["rules"][0];
        assert!(
            rule["filters"].is_null(),
            "S3 signatures require unmodified paths and Host"
        );
        assert_eq!(rule["matches"][0]["path"]["value"], "/");
        assert_eq!(
            rule["backendRefs"][0]["name"],
            service.metadata.name.unwrap()
        );
        assert_eq!(
            rule["backendRefs"][0]["port"].as_i64().unwrap(),
            i64::from(service.spec.unwrap().ports.unwrap()[0].port)
        );
        if endpoint == "api" {
            assert_eq!(route["spec"]["hostnames"][1], "*.s3.example.com");
            assert_eq!(rule["timeouts"]["request"], "600s");
        }
    }
    assert_resource_boundary(&docs);
}

#[test]
fn backend_tls_policies_target_each_service_with_explicit_trust() {
    let docs = documents(render(
        "{}",
        &[
            "deploy/rustfs-tenant/examples/gateway.yaml",
            "deploy/rustfs-tenant/examples/backend-tls.yaml",
        ],
    ));
    assert_eq!(docs.len(), 5);
    assert!(tenant(&docs).spec.tls.is_some());
    let policies: Vec<_> = docs
        .iter()
        .filter(|d| d["kind"] == "BackendTLSPolicy")
        .collect();
    assert_eq!(policies.len(), 2);
    for policy in policies {
        let service = policy["spec"]["targetRefs"][0]["name"].as_str().unwrap();
        assert!(["rustfs-io", "rustfs-console"].contains(&service));
        assert_eq!(
            policy["spec"]["validation"]["hostname"],
            format!("{service}.rustfs-storage.svc.cluster.local")
        );
        assert_eq!(
            policy["spec"]["validation"]["caCertificateRefs"][0]["name"],
            "rustfs-backend-ca"
        );
    }
    assert_resource_boundary(&docs);
}

#[test]
fn endpoints_can_be_disabled_without_leaving_route_or_policy_resources() {
    let docs = documents(render(
        r#"
httpRoute:
  api:
    enabled: false
  console:
    enabled: false
"#,
        &[
            "deploy/rustfs-tenant/examples/gateway.yaml",
            "deploy/rustfs-tenant/examples/backend-tls.yaml",
        ],
    ));
    assert_eq!(docs.len(), 1);
    assert_eq!(docs[0]["kind"], "Tenant");
}

#[test]
fn endpoints_can_choose_different_frontends_and_preserve_native_metadata() {
    let docs = documents(render(
        r#"
ingress:
  api:
    enabled: true
    hosts: [s3.example.com, "*.s3.example.com"]
    labels: {team: storage}
    annotations: {example.com/policy: streaming}
httpRoute:
  console:
    enabled: true
    parentRefs: [{name: shared, sectionName: https, port: 443}]
    hostnames: [console.example.com]
"#,
        &[],
    ));
    assert_eq!(docs.len(), 3);
    let ingress = docs.iter().find(|d| d["kind"] == "Ingress").unwrap();
    assert_eq!(ingress["metadata"]["labels"]["team"], "storage");
    assert_eq!(
        ingress["metadata"]["annotations"]["example.com/policy"],
        "streaming"
    );
    assert_eq!(ingress["spec"]["rules"][1]["host"], "*.s3.example.com");
    let route = docs.iter().find(|d| d["kind"] == "HTTPRoute").unwrap();
    assert_eq!(route["metadata"]["name"], "rustfs-console");
    assert_eq!(route["spec"]["parentRefs"][0]["port"].as_i64(), Some(443));
    assert_resource_boundary(&docs);
}

#[test]
fn invalid_networking_values_fail_offline_instead_of_silently_exposing() {
    for values in [
        "ingress: {api: {enabled: true}}",
        "httpRoute: {api: {enabled: true}}",
        "ingress: {api: {enabled: true, hosts: [s3.example.com]}}\nhttpRoute: {api: {enabled: true}}",
        "tenant: {metadata: {name: 9invalid}}",
        "tenant: {spec: {pools: []}}",
        "httpRoute: {api: {enabled: true, parentRefs: [{name: shared, kind: Service}], hostnames: [s3.example.com]}}",
        "httpRoute: {api: {backendTLS: {hostname: s3.example.com}}}",
        "ingress: {api: {enable: true}}",
    ] {
        let output = render(values, &[]);
        assert!(
            !output.status.success(),
            "invalid values unexpectedly rendered: {values}"
        );
        assert!(!output.stderr.is_empty());
    }
}

#[test]
fn plain_yaml_examples_use_the_same_service_contract() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let base = std::fs::read_to_string(root.join("examples/networking/base/tenant.yaml")).unwrap();
    let tenant: Tenant = serde_yaml_ng::from_str(&base).unwrap();
    tenant.validate_pools().unwrap();
    for file in [
        "ingress/ingress.yaml",
        "gateway/httproute.yaml",
        "gateway/backend-tls.yaml",
    ] {
        let yaml = std::fs::read_to_string(root.join("examples/networking").join(file)).unwrap();
        for doc in serde_yaml_ng::Deserializer::from_str(&yaml) {
            let value = Value::deserialize(doc).unwrap();
            let name = value["metadata"]["name"].as_str().unwrap();
            let service = if name == "rustfs-api" {
                tenant.new_io_service()
            } else {
                tenant.new_console_service()
            };
            let target = match value["kind"].as_str().unwrap() {
                "Ingress" => {
                    &value["spec"]["rules"][0]["http"]["paths"][0]["backend"]["service"]["name"]
                }
                "HTTPRoute" => &value["spec"]["rules"][0]["backendRefs"][0]["name"],
                "BackendTLSPolicy" => &value["spec"]["targetRefs"][0]["name"],
                other => panic!("unexpected example resource: {other}"),
            };
            assert_eq!(target.as_str(), service.metadata.name.as_deref());
        }
    }
}
