apiVersion: rustfs.com/v1alpha1
kind: Tenant
metadata:
  name: multi-pool-tenant
  namespace: rustfs-system
spec:
  image: rustfs/rustfs:latest

  # Multiple pools for distributed storage
  pools:
    - name: pool-0
      servers: 4
      persistence:
        volumesPerServer: 2

    - name: pool-1
      servers: 2
      persistence:
        volumesPerServer: 4

  # Optional: Environment variables
  # Note: Operator automatically sets RUSTFS_VOLUMES, RUSTFS_ADDRESS,
  # RUSTFS_CONSOLE_ADDRESS, and RUSTFS_CONSOLE_ENABLE
  env:
    # Standard Rust logging (not RustFS-specific)
    - name: RUST_LOG
      value: "debug"

  # Optional: Custom scheduler
  # scheduler: default-scheduler
