{{- if and .Values.cosiDriver.enabled .Values.cosiDriver.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rustfs-operator.fullname" . }}-cosi-driver
  labels:
    {{- include "rustfs-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: cosi-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rustfs-operator.fullname" . }}-cosi-driver
subjects:
  - kind: ServiceAccount
    name: {{ include "rustfs-operator.cosiDriverServiceAccountName" . }}
    namespace: {{ include "rustfs-operator.namespace" . }}
{{- end }}
