{{- if and .Values.operator.metrics.enabled .Values.operator.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rustfs-operator.fullname" . }}
  namespace: {{ include "rustfs-operator.namespace" . }}
  labels:
    {{- include "rustfs-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
    {{- with .Values.operator.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.operator.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "rustfs-operator.namespace" . }}
  selector:
    matchLabels:
      {{- include "rustfs-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.operator.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.operator.serviceMonitor.scrapeTimeout }}
{{- end }}
