{{/*
Copyright 2026 RustFS Team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{- $name := include "rustfs-tenant.name" . -}}
{{- range $endpoint := list "api" "console" }}
{{- $config := index $.Values.httpRoute $endpoint }}
{{- if $config.enabled }}
{{- $service := printf "%s-console" $name }}
{{- $port := 9001 }}
{{- if eq $endpoint "api" }}
{{- $service = printf "%s-io" $name }}
{{- $port = 9000 }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}-{{ $endpoint }}
  namespace: {{ $.Release.Namespace }}
  {{- with $config.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml $config.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml $config.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $service }}
          port: {{ $port }}
      {{- with $config.timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- with $config.backendTLS }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ $name }}-{{ $endpoint }}
  namespace: {{ $.Release.Namespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ $service }}
  validation:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
